### ISSUE TITLE
In values.yml the tag that is provided for dataFetcher , dataStore and syncElastic leads me to that error:

### ISSUE THREAD

**Issue by jeromegv** [IlyaKreynin/citizen-dashboard#35]
On a Mac with ARM processor (M1,M2,M3,M4, etc), out of the box, running `python civic-dashboard/scripts/deploy_local.py` does not work

Instead, manually running `helm upgrade --install civic-dashboard ./civic-dashboard --namespace civic-dashboard  --create-namespace` also does not work

I was able to narrow down the problem to the fact that docker cannot pull the services images.

when I try to run `docker pull ghcr.io/civic-dashboard/data-fetcher:main-b068c745feeaf88fb0353e0669d104c4701b0d38`  I get this error:

`Error response from daemon: no matching manifest for linux/arm64/v8 in the manifest list entries: no match for platform in manifest: not found`

<img width="1390" alt="Image" src="https://github.com/user-attachments/assets/c5706e55-9396-44c2-8642-8233335bffc9" />

I get the same error in values.yml for the tags that are provided for `dataFetcher`  `dataStore` and `syncElastic`

So I went to the repository links, such as https://github.com/civic-dashboard/civic-dashboard/pkgs/container/data-fetcher, and instead of doing a `docker pull` from the installation tab, I went to the `OS / Arch` tab and I can do a docker pull from the `linux/amd64` architecture

So as a temporary workaround, I ended up updating values.yaml and change the tag value to use the one from `linux/amd64` for the 3 services

```
images:
  dataFetcher:
    repository: ghcr.io/civic-dashboard/data-fetcher
    tag: main-b068c745feeaf88fb0353e0669d104c4701b0d38@sha256:c2b4b1bd76ccde503d724291aa6e6ea3b1a9547f83b7c9a2b25e605cd03e995b                       
    pullPolicy: IfNotPresent

  dataStore:
    repository: ghcr.io/civic-dashboard/data-store
    tag: main-b068c745feeaf88fb0353e0669d104c4701b0d38@sha256:2f1edc86e477da2e97a637288037e740d863e24ea122ceaaf6cececa3b13fc01                     
    pullPolicy: IfNotPresent

  syncElastic:
    repository: ghcr.io/civic-dashboard/sync-elastic
    tag: main-b068c745feeaf88fb0353e0669d104c4701b0d38@sha256:4bfa2b6b56116adcdf262a665ae38116d1d404acab7a9424a479908f62cb82db             
    pullPolicy: IfNotPresent
```

It seems like the fix should be for the manifest to automatically use the `linux/amd64` architecture if no docker builds are found for `linux/arm64/v8` (as Docker Desktop on Mac can emulate the x86_64/amd64 architectures)
